# Generated by Django 5.2.8 on 2026-03-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_style', '0002_per_ball_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstyle',
            name='credits_auto_color',
            field=models.BooleanField(default=True, help_text='Auto-picks black or white based on background. Uncheck to set manually.', verbose_name='Auto-detect Credits Color'),
        ),
        migrations.AlterField(
            model_name='cardstyle',
            name='name',
            field=models.CharField(help_text="A label for this style preset (e.g. 'Gold Theme', 'LeBron Special')", max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='cardstyle',
            name='title_glow_radius',
            field=models.IntegerField(default=0, help_text='Glow blur radius in pixels (0 = none)', verbose_name='Glow Radius'),
        ),
        migrations.AlterField(
            model_name='cardstyle',
            name='title_gradient_end',
            field=models.CharField(blank=True, default='', help_text='Leave empty for solid. Set a color to enable gradient.', max_length=7, verbose_name='Gradient End Color'),
        ),
        migrations.AlterField(
            model_name='cardstyle',
            name='title_stroke_width',
            field=models.IntegerField(default=2, help_text='Outline thickness in pixels (0 = none)', verbose_name='Stroke Width'),
        ),
    ]
