# Generated by Django 5.2.8 on 2026-04-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0010_ball_packable'),
        ('card_style', '0003_alter_cardstyle_credits_auto_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstyle',
            name='special',
            field=models.ForeignKey(blank=True, help_text='Apply this style to ALL cards with this special. Leave empty to use the balls list instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_styles', to='bd_models.special'),
        ),
    ]
