server {
    listen 80;
    # TODO: replace Patreon Name here
    server_name nbadex.ballsdex.com;
    client_max_body_size 100m;

    location / {
        proxy_set_header Host $http_host;
        # TODO: replace port number here
        proxy_pass http://127.0.0.1:8001/;
    }
    location ~ ^/(static|media)/ {
        # TODO: replace path here
        root /home/ballsdex/Shabnum/admin_panel;
    }
}
