# Generated by Django 5.2.8 on 2026-01-21 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_id', models.BigIntegerField()),
                ('player2_id', models.BigIntegerField()),
                ('winner_id', models.BigIntegerField(default=None, null=True)),
                ('bet_date', models.DateTimeField(auto_now_add=True)),
                ('player1_count', models.IntegerField(default=0)),
                ('player2_count', models.IntegerField(default=0)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(default=None, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_initiated', to='bd_models.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_received', to='bd_models.player')),
                ('winner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bets_won', to='bd_models.player')),
            ],
        ),
        migrations.CreateModel(
            name='BetStake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betstakes', to='bd_models.ballinstance')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betstakes', to='betting.bet')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betstakes', to='bd_models.player')),
            ],
        ),
    ]
