# Generated by Django 5.2.8 on 2026-01-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quicksell_value', models.IntegerField(default=100, help_text='Coins received when quickselling this ball')),
                ('ball', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pack name', max_length=64, unique=True)),
                ('description', models.TextField(default=None, help_text='Pack description', null=True)),
                ('emoji', models.CharField(default=None, help_text='Emoji for this pack', max_length=64, null=True)),
                ('price', models.IntegerField(help_text='Price in coins to buy this pack')),
                ('cards_count', models.IntegerField(default=1, help_text='Number of cards in this pack')),
                ('min_rarity', models.FloatField(default=0.0, help_text='Minimum rarity of balls in this pack')),
                ('max_rarity', models.FloatField(default=100.0, help_text='Maximum rarity of balls in this pack')),
                ('special_only', models.BooleanField(default=False, help_text='Only include special cards in this pack')),
                ('daily_limit', models.IntegerField(default=0, help_text='Maximum packs a player can open per day (0 = unlimited)')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this pack is available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('special', models.ForeignKey(default=None, help_text='Optional: only give balls from this special event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.special')),
            ],
        ),
        migrations.CreateModel(
            name='PackOpenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('cards_received', models.IntegerField(default=1, help_text='Number of cards received')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_opens', to='coins.pack')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_opens', to='bd_models.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0, help_text='Player coins')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_models.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Number of packs owned')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerpacks', to='coins.pack')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerpacks', to='bd_models.player')),
            ],
            options={
                'unique_together': {('player', 'pack')},
            },
        ),
    ]
