# Generated by Django 5.2.8 on 2026-03-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='special',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional: only give balls from this special event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.special'),
        ),
    ]
