# Generated by Django 5.2.8 on 2026-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_pack_multi_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballvalue',
            name='catch_value',
            field=models.IntegerField(default=100, help_text='Coins earned when catching this ball from a natural/admin spawn (0 = no reward)'),
        ),
    ]
