"""
NBA player positions for the Battle system — 2025-26 season (full rosters, March 28 2026).
Maps player names to (primary, secondary) positions.
Positions: PG, SG, SF, PF, C

Name lookup is accent-insensitive and case-insensitive.
"Jr.", "Jr", "jr.", "jr" are all treated the same.
"""

import re
import unicodedata

NBA_POSITIONS: dict[str, tuple[str, str | None]] = {

    # ─── POINT GUARDS ─────────────────────────────────────────────────────────
    "Stephen Curry":             ("PG", None),
    "Luka Doncic":               ("PG", "SG"),
    "Damian Lillard":            ("PG", None),
    "Ja Morant":                 ("PG", None),
    "Trae Young":                ("PG", None),
    "Tyrese Haliburton":         ("PG", None),
    "Jalen Brunson":             ("PG", None),
    "Shai Gilgeous-Alexander":   ("PG", "SG"),
    "Kyrie Irving":              ("PG", "SG"),
    "Cade Cunningham":           ("PG", "SG"),
    "Tyrese Maxey":              ("PG", "SG"),
    "LaMelo Ball":               ("PG", "SG"),
    "Scoot Henderson":           ("PG", None),
    "D'Angelo Russell":          ("PG", "SG"),
    "Darius Garland":            ("PG", None),
    "Immanuel Quickley":         ("PG", "SG"),
    "Josh Giddey":               ("PG", "SG"),
    "Dejounte Murray":           ("PG", "SG"),
    "Terry Rozier":              ("PG", "SG"),
    "Payton Pritchard":          ("PG", None),
    "Tre Jones":                 ("PG", None),
    "Cole Anthony":              ("PG", "SG"),
    "Tyus Jones":                ("PG", None),
    "Ayo Dosunmu":               ("PG", "SG"),
    "Dennis Schroder":           ("PG", None),
    "Fred VanVleet":             ("PG", None),
    "De'Aaron Fox":              ("PG", None),
    "Markelle Fultz":            ("PG", None),
    "Jamal Murray":              ("PG", "SG"),
    "Coby White":                ("PG", "SG"),
    "Jalen Suggs":               ("PG", "SG"),
    "Andrew Nembhard":           ("PG", "SG"),
    "Keyonte George":            ("PG", None),
    "Stephon Castle":            ("PG", "SG"),
    "Carlton Carrington":        ("PG", None),
    "Rob Dillingham":            ("PG", None),
    "Nikola Topic":              ("PG", None),
    "Isaiah Collier":            ("PG", None),
    "Collin Sexton":             ("PG", "SG"),
    "Malik Monk":                ("PG", "SG"),
    "Jordan Clarkson":           ("SG", "PG"),
    "TJ McConnell":              ("PG", None),
    "Kris Dunn":                 ("PG", "SG"),
    "Davion Mitchell":           ("PG", "SG"),
    "Scotty Pippen Jr.":         ("PG", None),
    "Craig Porter Jr.":          ("PG", None),
    "JD Davison":                ("PG", None),
    "Jose Alvarado":             ("PG", "SG"),
    "Aaron Holiday":             ("PG", None),
    "Delon Wright":              ("PG", "SG"),
    "Devonte' Graham":           ("PG", "SG"),
    "Seth Curry":                ("SG", "PG"),
    "Gabe Vincent":              ("PG", "SG"),
    "Dalano Banton":             ("PG", None),
    "Jordan McLaughlin":         ("PG", None),

    # ─── SHOOTING GUARDS ──────────────────────────────────────────────────────
    "Jalen Williams":            ("SG", "PG"),
    "Donovan Mitchell":          ("SG", "PG"),
    "Devin Booker":              ("SG", "PG"),
    "Klay Thompson":             ("SG", None),
    "Bradley Beal":              ("SG", "PG"),
    "Jaylen Brown":              ("SG", "SF"),
    "Anthony Edwards":           ("SG", "PG"),
    "Jalen Green":               ("SG", "PG"),
    "CJ McCollum":               ("SG", "PG"),
    "Paul George":               ("SG", "SF"),
    "Tyler Herro":               ("SG", "PG"),
    "Malik Beasley":             ("SG", None),
    "Buddy Hield":               ("SG", None),
    "Devin Vassell":             ("SG", "PG"),
    "RJ Barrett":                ("SG", "SF"),
    "Desmond Bane":              ("SG", "SF"),
    "Donte DiVincenzo":          ("SG", None),
    "Gary Trent Jr.":            ("SG", None),
    "Max Strus":                 ("SG", "SF"),
    "Duncan Robinson":           ("SG", "SF"),
    "Norman Powell":             ("SG", "SF"),
    "Amen Thompson":             ("SG", "PG"),
    "Zach LaVine":               ("SG", "PG"),
    "DeMar DeRozan":             ("SG", "SF"),
    "Tim Hardaway Jr.":          ("SG", None),
    "Bogdan Bogdanovic":         ("SG", "SF"),
    "Luguentz Dort":             ("SG", "SF"),
    "Josh Hart":                 ("SG", "SF"),
    "Dillon Brooks":             ("SG", "SF"),
    "Isaiah Joe":                ("SG", None),
    "Brandon Miller":            ("SG", "SF"),
    "Trey Murphy III":           ("SG", "SF"),
    "Dalton Knecht":             ("SG", "SF"),
    "Jaylen Wells":              ("SG", "SF"),
    "Ben Sheppard":              ("SG", "SF"),
    "James Harden":              ("SG", "PG"),
    "Cody Williams":             ("SG", "SF"),
    "Alex Caruso":               ("SG", "PG"),
    "Shaedon Sharpe":            ("SG", "SF"),
    "Grayson Allen":             ("SG", None),
    "Gradey Dick":               ("SG", "SF"),
    "Bennedict Mathurin":        ("SG", "SF"),
    "Reed Sheppard":             ("SG", "PG"),
    "Jared McCain":              ("SG", "PG"),
    "Josh Green":                ("SG", "SF"),
    "Moses Moody":               ("SG", "SF"),
    "Bilal Coulibaly":           ("SG", "SF"),
    "Anfernee Simons":           ("SG", "PG"),
    "Austin Reaves":             ("SG", "PG"),
    "Nickeil Alexander-Walker":  ("SG", "PG"),
    "Derrick White":             ("PG", "SG"),
    "Brandin Podziemski":        ("SG", "PG"),
    "Cam Thomas":                ("SG", "PG"),
    "Dyson Daniels":             ("SG", "PG"),
    "Jordan Poole":              ("SG", "PG"),
    "Gary Payton II":            ("PG", "SG"),
    "Dalen Terry":               ("SG", "SF"),
    "Kevin Huerter":             ("SG", "SF"),
    "Malaki Branham":            ("SG", "PG"),
    "Tre Mann":                  ("SG", "PG"),
    "Brice Sensabaugh":          ("SG", "SF"),
    "Jordan Walsh":              ("SF", "SG"),
    "Isaac Okoro":               ("SG", "SF"),
    "Sam Merrill":               ("SG", None),
    "Keon Johnson":              ("SG", "PG"),
    "Ochai Agbaji":              ("SG", "SF"),
    "MarJon Beauchamp":          ("SF", "SG"),
    "Andre Jackson Jr.":         ("SG", "SF"),
    "Pat Connaughton":           ("SG", "SF"),
    "Blake Wesley":              ("SG", "PG"),
    "Aaron Wiggins":             ("SG", "SF"),
    "Marcus Sasser":             ("SG", "PG"),
    "Jalen Wilson":              ("SF", "SG"),
    "Joe Harris":                ("SG", "SF"),
    "Luke Kennard":              ("SG", None),
    "Hamidou Diallo":            ("SG", "SF"),
    "Troy Brown Jr.":            ("SG", "SF"),
    "Johnny Davis":              ("SG", None),
    "Corey Kispert":             ("SF", "SG"),

    # ─── SMALL FORWARDS ───────────────────────────────────────────────────────
    "LeBron James":              ("SF", "PF"),
    "Kevin Durant":              ("SF", "PF"),
    "Jayson Tatum":              ("SF", "PF"),
    "Brandon Ingram":            ("SF", "PF"),
    "Franz Wagner":              ("SF", "SG"),
    "Mikal Bridges":             ("SF", "SG"),
    "OG Anunoby":                ("SF", "SG"),
    "Andrew Wiggins":            ("SF", "SG"),
    "Michael Porter Jr.":        ("SF", "SG"),
    "Khris Middleton":           ("SF", "SG"),
    "Sam Hauser":                ("SF", "SG"),
    "Ausar Thompson":            ("SF", "SG"),
    "Herbert Jones":             ("SF", None),
    "Dorian Finney-Smith":       ("SF", None),
    "Keldon Johnson":            ("SF", None),
    "Harrison Barnes":           ("SF", "PF"),
    "Jaden McDaniels":           ("SF", "PF"),
    "Royce O'Neale":             ("SF", None),
    "Jake LaRavia":              ("SF", "PF"),
    "Kenyon Martin Jr.":         ("SF", "PF"),
    "Matisse Thybulle":          ("SF", "SG"),
    "Jalen Johnson":             ("SF", "PF"),
    "Jimmy Butler":              ("SF", "SG"),
    "Kawhi Leonard":             ("SF", "SG"),
    "Kyle Kuzma":                ("SF", "PF"),
    "Tari Eason":                ("SF", "PF"),
    "Matas Buzelis":             ("SF", "PF"),
    "Nikola Jovic":              ("SF", "PF"),
    "Zaccharie Risacher":        ("SF", None),
    "Tidjane Salaun":            ("SF", None),
    "Miles Bridges":             ("PF", "SF"),
    "Ron Holland II":            ("SF", "SG"),
    "Deni Avdija":               ("SF", "PF"),
    "GG Jackson II":             ("SF", "PF"),
    "Patrick Williams":          ("PF", "SF"),
    "Rui Hachimura":             ("SF", "PF"),
    "Aaron Nesmith":             ("SF", "SG"),
    "Caleb Houstan":             ("SF", "SG"),
    "Jeremy Sochan":             ("PF", "SF"),
    "Ryan Dunn":                 ("SF", "SG"),
    "Kentavious Caldwell-Pope":  ("SG", "SF"),
    "De'Andre Hunter":           ("SF", "SG"),
    "Kyle Anderson":             ("SF", "PF"),
    "Simone Fontecchio":         ("SF", "PF"),
    "Josh Okogie":               ("SF", "SG"),
    "Nassir Little":             ("SF", "PF"),
    "Peyton Watson":             ("SF", "PF"),
    "Julian Strawther":          ("SF", "SG"),
    "Christian Braun":           ("SG", "SF"),
    "Kenrich Williams":          ("SF", "PF"),
    "Torrey Craig":              ("SF", "PF"),
    "Max Christie":              ("SG", "SF"),
    "Haywood Highsmith":         ("SF", "PF"),
    "Ziaire Williams":           ("SF", "SG"),
    "Noah Clowney":              ("PF", "SF"),
    "Vit Krejci":                ("PG", "SG"),
    "Mouhamed Gueye":            ("C",  "PF"),
    "Dean Wade":                 ("PF", "SF"),
    "Naji Marshall":             ("SF", "SG"),
    "Quentin Grimes":            ("SG", "SF"),
    "Jaden Hardy":               ("SG", "PG"),
    "Maxi Kleber":               ("PF", "C"),
    "Georges Niang":             ("PF", "SF"),
    "Joe Ingles":                ("SF", None),
    "Josh Minott":               ("SF", "PF"),
    "Chris Boucher":             ("PF", "C"),
    "Tristan da Silva":          ("SF", "PF"),
    "Oso Ighodaro":              ("C",  "PF"),
    "Bruce Brown":               ("PG", "SG"),
    "Garrison Mathews":          ("SG", None),
    "Bojan Bogdanovic":          ("SF", "SG"),
    "Dario Saric":               ("PF", "SF"),
    "Caris LeVert":              ("SG", "PG"),

    # ─── POWER FORWARDS ───────────────────────────────────────────────────────
    "Giannis Antetokounmpo":     ("PF", "C"),
    "Anthony Davis":             ("PF", "C"),
    "Zion Williamson":           ("PF", "C"),
    "Julius Randle":             ("PF", "SF"),
    "Pascal Siakam":             ("PF", "SF"),
    "Evan Mobley":               ("PF", "C"),
    "Scottie Barnes":            ("PF", "SF"),
    "Paolo Banchero":            ("PF", "SF"),
    "Jabari Smith Jr.":          ("PF", "C"),
    "John Collins":              ("PF", "C"),
    "Lauri Markkanen":           ("PF", "C"),
    "Bobby Portis":              ("PF", "C"),
    "Aaron Gordon":              ("PF", "SF"),
    "Jerami Grant":              ("PF", "SF"),
    "Draymond Green":            ("PF", "C"),
    "P.J. Washington":           ("PF", "C"),
    "Keegan Murray":             ("PF", "SF"),
    "Tobias Harris":             ("PF", "SF"),
    "Precious Achiuwa":          ("PF", "C"),
    "Jabari Walker":             ("PF", "SF"),
    "Jonathan Kuminga":          ("PF", "SF"),
    "Marvin Bagley III":         ("PF", "C"),
    "Grant Williams":            ("PF", "SF"),
    "Jarace Walker":             ("PF", "SF"),
    "Larry Nance Jr.":           ("PF", "C"),
    "Onyeka Okongwu":            ("C",  "PF"),
    "KJ Martin":                 ("PF", "SF"),
    "Trendon Watford":           ("PF", "SF"),
    "Saddiq Bey":                ("SF", "PF"),
    "Chet Holmgren":             ("C",  "PF"),
    "Jonathan Isaac":            ("PF", "SF"),
    "Obi Toppin":                ("PF", "C"),
    "Isaiah Jackson":            ("C",  "PF"),
    "Christian Wood":            ("PF", "C"),
    "Zeke Nnaji":                ("PF", "C"),
    "Jeremiah Robinson-Earl":    ("PF", "C"),
    "Neemias Queta":             ("C",  "PF"),

    # ─── CENTERS ──────────────────────────────────────────────────────────────
    "Nikola Jokic":              ("C",  "PF"),
    "Joel Embiid":               ("C",  "PF"),
    "Victor Wembanyama":         ("C",  "PF"),
    "Bam Adebayo":               ("C",  "PF"),
    "Karl-Anthony Towns":        ("C",  "PF"),
    "Jaren Jackson Jr.":         ("C",  "PF"),
    "Rudy Gobert":               ("C",  None),
    "Brook Lopez":               ("C",  None),
    "Myles Turner":              ("C",  "PF"),
    "Alperen Sengun":            ("C",  "PF"),
    "Domantas Sabonis":          ("C",  "PF"),
    "Kristaps Porzingis":        ("C",  "PF"),
    "Nikola Vucevic":            ("C",  "PF"),
    "Al Horford":                ("C",  "PF"),
    "Mitchell Robinson":         ("C",  None),
    "Naz Reid":                  ("C",  "PF"),
    "Luke Kornet":               ("C",  None),
    "Daniel Gafford":            ("C",  None),
    "Clint Capela":              ("C",  None),
    "Jarrett Allen":             ("C",  None),
    "Ivica Zubac":               ("C",  None),
    "Deandre Ayton":             ("C",  "PF"),
    "Isaiah Stewart":            ("C",  "PF"),
    "Nic Claxton":               ("C",  None),
    "Isaiah Hartenstein":        ("C",  None),
    "Jakob Poeltl":              ("C",  None),
    "Kelly Olynyk":              ("C",  "PF"),
    "Andre Drummond":            ("C",  None),
    "Moritz Wagner":             ("C",  "PF"),
    "Walker Kessler":            ("C",  None),
    "Drew Eubanks":              ("C",  None),
    "Nick Richards":             ("C",  None),
    "Day'Ron Sharpe":            ("C",  None),
    "Jaxson Hayes":              ("C",  None),
    "Mark Williams":             ("C",  None),
    "Donovan Clingan":           ("C",  None),
    "Yves Missi":                ("C",  None),
    "Zach Collins":              ("C",  "PF"),
    "Xavier Tillman":            ("C",  "PF"),
    "Wendell Carter Jr.":        ("C",  "PF"),
    "Thomas Bryant":             ("C",  None),
    "Trey Lyles":                ("C",  "PF"),
    "Mason Plumlee":             ("C",  None),
    "Tristan Thompson":          ("C",  None),
    "Charles Bassey":            ("C",  None),
    "Goga Bitadze":              ("C",  None),
    "Jericho Sims":              ("C",  None),
    "Jalen Duren":               ("C",  None),
    "Trayce Jackson-Davis":      ("C",  "PF"),
    "Zach Edey":                 ("C",  None),
    "Kevon Looney":              ("C",  None),
    "Robert Williams III":       ("C",  None),
    "Bismack Biyombo":           ("C",  None),
    "Moussa Diabate":            ("C",  "PF"),
    "Daniel Theis":              ("C",  "PF"),
    "Tristan Vukcevic":          ("C",  "PF"),
    "Jalen Smith":               ("C",  "PF"),
    "Alex Len":                  ("C",  None),
}

VALID_POSITIONS = {"PG", "SG", "SF", "PF", "C"}

POSITION_LABELS = {
    "PG": "Point Guard",
    "SG": "Shooting Guard",
    "SF": "Small Forward",
    "PF": "Power Forward",
    "C":  "Center",
}


# ─── Name normalisation ───────────────────────────────────────────────────────

def _normalize_name(name: str) -> str:
    """
    Strip accents, lowercase, and normalise common suffixes so that
    e.g. "Nikola Jokić", "nikola jokic", "Jaren Jackson Jr.",
    "Jaren Jackson Jr", "jaren jackson jr" all map to the same key.
    """
    # 1. Decompose Unicode → strip combining diacritics
    s = unicodedata.normalize("NFD", name)
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    # 2. Lowercase
    s = s.lower()
    # 3. Normalise suffixes — remove trailing period after Jr/Sr/II/III/IV/V
    s = re.sub(r"\bjr\.", "jr", s)
    s = re.sub(r"\bsr\.", "sr", s)
    # 4. Collapse whitespace
    s = re.sub(r"\s+", " ", s).strip()
    return s


# Pre-built lookup: normalised_name → (primary, secondary)
_NORMALISED: dict[str, tuple[str, str | None]] = {
    _normalize_name(k): v for k, v in NBA_POSITIONS.items()
}


def get_position_for_name(name: str) -> tuple[str, str | None] | None:
    """
    Look up a player's (primary, secondary) position by name.
    Accepts any capitalisation, with or without diacritics,
    and 'Jr.' / 'Jr' interchangeably.
    Returns None if the player is not in the registry.
    """
    return _NORMALISED.get(_normalize_name(name))
