# Generated by Django 5.2.8 on 2026-04-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0012_special_battle_bonuses'),
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collectorrequirement',
            name='unique_collector_requirement',
        ),
        migrations.RemoveConstraint(
            model_name='playercollectorcard',
            name='unique_player_collector_card',
        ),
        migrations.AlterField(
            model_name='collectorcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collectorrequirement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='playercollectorcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='collectorrequirement',
            unique_together={('card', 'ball')},
        ),
        migrations.AlterUniqueTogether(
            name='playercollectorcard',
            unique_together={('player', 'card', 'ball')},
        ),
    ]
